#!/usr/bin/env bash
# Re-vendor the agent skills from the taskrail release pinned in mise.toml.
#
# Usage: scripts/vendor-skills.sh [--check]
#
# Every skill under .agents/skills/ and .claude/skills/ is a byte-exact copy of
# the skill package embedded in the pinned taskrail release. Nothing here is
# locally authored, so the trees are regenerated rather than edited.
#
# Why the module cache and not `taskrail init --with-skills`:
#
#   1. That command stamps a `taskrail_version` marker derived from the running
#      binary's version, which is a GoReleaser ldflag. A `go install` build (what
#      the mise backend produces) reports 0.0.0-dev, so it would stamp 0.0.0-dev
#      and every release-built binary would then report version skew against it.
#   2. taskrail suppresses skew warnings entirely for a skill that is unstamped
#      and byte-identical to the package the running binary embeds — see
#      isPackageParityCopy in taskrail's internal/taskrail/skills_skew.go. Copying
#      the package source is the supported way to land in that state.
#   3. `--force` writes SKILL.md.bak.<timestamp> siblings into both trees. The
#      pinned-package check rejects those extra files, but they should never be
#      created in this repository.
#
# The digest manifest is regenerated here so it can never drift from the trees.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

manifest="docs/workflow/skills-manifest.yml"
module="github.com/tessariq/taskrail"
trees=(.agents/skills .claude/skills)

mode="${1:-vendor}"
if [[ "$mode" != "vendor" && "$mode" != "--check" ]] || [[ $# -gt 1 ]]; then
  echo "usage: scripts/vendor-skills.sh [--check]" >&2
  exit 2
fi

# mise.toml is the single source of truth for the version; reading it here keeps
# the vendored trees and the toolchain pin from drifting apart.
version="$(sed -n 's/^"go:github\.com\/tessariq\/taskrail\/cmd\/taskrail" *= *"\([^"]*\)".*/\1/p' mise.toml)"
if [[ -z "$version" ]]; then
  echo "vendor-skills: could not read the taskrail pin from mise.toml" >&2
  exit 1
fi

src="$(go mod download -json "${module}@v${version}" | sed -n 's/^[[:space:]]*"Dir": "\(.*\)",\?$/\1/p')/internal/taskrail/skills"
if [[ ! -d "$src" ]]; then
  echo "vendor-skills: embedded skill package not found at ${src}" >&2
  exit 1
fi

if [[ "$mode" == "--check" ]]; then
  for tree in "${trees[@]}"; do
    if ! diff -rq "$src" "$tree"; then
      echo "vendor-skills: ${tree} does not match ${module}@v${version}" >&2
      exit 1
    fi
  done
  echo "vendored skill trees match ${module}@v${version}"
  exit 0
fi

for tree in "${trees[@]}"; do
  rm -rf "$tree"
  mkdir -p "$tree"
  cp -R "$src/." "$tree/"
  # The module cache is read-only; restore write permission so the working tree
  # behaves normally for the next re-vendor.
  chmod -R u+w "$tree"
done

{
  echo "# Provenance for the mirrored agent skill trees (.agents/skills, .claude/skills)."
  echo "#"
  echo "# Every skill is a byte-exact copy of the skill package embedded in the pinned"
  echo "# taskrail release. None of them is locally authored, so none may be hand-edited:"
  echo "# an edit is lost on the next re-vendor and fails task workflow:check-skills in"
  echo "# the meantime. Regenerate with 'task workflow:skills:vendor'."
  echo "#"
  echo "# Generated by scripts/vendor-skills.sh. Do not edit by hand."
  echo "schema_version: 1"
  echo "taskrail_version: \"${version}\""
  echo "skills:"
  for skill in $(ls .agents/skills | sort); do
    digest="$(sha256sum ".agents/skills/${skill}/SKILL.md" | cut -d' ' -f1)"
    echo "  - name: ${skill}"
    echo "    sha256: ${digest}"
  done
} >"$manifest"

echo "vendored ${#trees[@]} trees from ${module}@v${version}; wrote ${manifest}"
